extends Node

enum ITEM_TYPE { OTHER, WEAPON, ARMOUR, POTION  }
enum WEAPON_QUALITY { NORMAL = 0, UNCOMMON, RARE, EPIC  }
enum ARMOUR_QUALITY { NORMAL = 10, UNCOMMON, RARE, EPIC  }
enum POTION_QUALITY { NORMAL = 20, UNCOMMON, RARE, EPIC  }


var item_collection : Dictionary = { 
WEAPON_QUALITY.NORMAL : "NormalWeapon",
WEAPON_QUALITY.UNCOMMON : "UncommonWeapon",
WEAPON_QUALITY.RARE : "RareWeapon",
WEAPON_QUALITY.EPIC : "EpicWeapon",

ARMOUR_QUALITY.NORMAL : "NormalArmour",
ARMOUR_QUALITY.UNCOMMON : "UncommonArmour",
ARMOUR_QUALITY.RARE : "RareArmour",
ARMOUR_QUALITY.EPIC : "EpicArmour",

POTION_QUALITY.NORMAL : "NormalPotion",
POTION_QUALITY.UNCOMMON : "UncommonPotion",
POTION_QUALITY.RARE : "RarePotion",
POTION_QUALITY.EPIC : "EpicPotion",
}

var item_collection_value : Dictionary = { 
WEAPON_QUALITY.NORMAL : 150,
WEAPON_QUALITY.UNCOMMON : 300,
WEAPON_QUALITY.RARE : 800,
WEAPON_QUALITY.EPIC : 2000,

ARMOUR_QUALITY.NORMAL : 150,
ARMOUR_QUALITY.UNCOMMON : 300,
ARMOUR_QUALITY.RARE : 800,
ARMOUR_QUALITY.EPIC : 2000,
}

var item_collection_penalty : Dictionary = { 
WEAPON_QUALITY.NORMAL : 250,
WEAPON_QUALITY.UNCOMMON : 600,
WEAPON_QUALITY.RARE : 2000,
WEAPON_QUALITY.EPIC : 10000,

ARMOUR_QUALITY.NORMAL : 250,
ARMOUR_QUALITY.UNCOMMON : 600,
ARMOUR_QUALITY.RARE : 2000,
ARMOUR_QUALITY.EPIC : 10000,
}

func _init():
	pass