extends Node

var current_stock_data = {
	BaseItem.WEAPON_QUALITY.NORMAL : 0,
	BaseItem.WEAPON_QUALITY.UNCOMMON : 0,
	BaseItem.WEAPON_QUALITY.RARE : 0,
	BaseItem.WEAPON_QUALITY.EPIC : 0,
	
	BaseItem.ARMOUR_QUALITY.NORMAL : 0,
	BaseItem.ARMOUR_QUALITY.UNCOMMON : 0,
	BaseItem.ARMOUR_QUALITY.RARE : 0,
	BaseItem.ARMOUR_QUALITY.EPIC : 0,
	
	BaseItem.POTION_QUALITY.NORMAL : 1,
	BaseItem.POTION_QUALITY.UNCOMMON : 0,
	BaseItem.POTION_QUALITY.RARE : 0,
	BaseItem.POTION_QUALITY.EPIC : 0,
}